### PR TITLE
Sending mails

### PR DESCRIPTION
**Pull request by ChiragJS**
1. Dont merge this pr for now , not complete, will make further commits
2. add the credentials in application-dev.properties to test the feature out in dev profile(username and password)
3. For testing purposes i called the mailing function on the root url for the app, will have to place the function calls on particular functions
4. Not yet implemented the logic for sending attachments 
5. No need for starttls property in application props , as we are using port 465
6. Will make the necessary changes in the next Commit on this branch

### CODE REVIEW

**Comment by ChiragJS** [comment]
This pr address the issue #61 Sending mails

**Comment by ChiragJS** [comment]
This pr addresses  issue #20

**Review by SundarakrishnanN — APPROVED** [review]
Looks good now..Maybe for later,we can keep beautification of mail upon user creation.

**Comment by Prajwalprakash3722** [comment]
I think you can keep the same template, change the template content

**Comment by SundarakrishnanN** [comment]
> I think you can keep the same template, change the template content

Yep,will do that before we go for the real launch..but can be merged for now

**Pull request merged**
